name: Build and Release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  build-release:
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    uses: LarsNieuwenhuizen/workflows/.github/workflows/build-and-release-go.yml@main
    with:
      app-name: hcldoc