name: Build and Release
on:
  workflow_dispatch:

jobs:
  version:
    uses: LarsNieuwenhuizen/workflows/.github/workflows/build-and-release-go.yml@feat/go-build-release-workflow

  use-version:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Use version
        run: echo "Using version ${{ needs.version.outputs.result }}"