name: Testing code

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  push:
    branches:
      - main

jobs:
    test:
      uses: LarsNieuwenhuizen/workflows/.github/workflows/test-go.yml@main
      with:
        path: "github.com/larsnieuwenhuizen/hcl-documenter-go/pkg/variable_files"